src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/business/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from business import api
from business.views import *
from business.wizards.bzProductCreate import *

# router = routers.DefaultRouter()
# router.register(r'bzbrand', api.bzBrandViewSet)
# router.register(r'bzcreativecollection', api.bzCreativeCollectionViewSet)
# router.register(r'bzcreativedesign', api.bzCreativeDesignViewSet)
# router.register(r'bzcreativelayout', api.bzCreativeLayoutViewSet)
# router.register(r'bzcreativerendering', api.bzCreativeRenderingViewSet)
# router.register(r'bzproduct', api.bzProductViewSet)
# router.register(r'bzproductvariant', api.bzProductVariantViewSet)
# router.register(r'wooattribute', api.wooAttributeViewSet)
# router.register(r'woocategory', api.wooCategoryViewSet)
# router.register(r'wooimage', api.wooImageViewSet)
# router.register(r'wooproduct', api.wooProductViewSet)
# router.register(r'wooshippingclass', api.wooShippingClassViewSet)
# router.register(r'woostore', api.wooStoreViewSet)
# router.register(r'wootag', api.wooTagViewSet)
# router.register(r'wooterm', api.wooTermViewSet)
# router.register(r'woovariant', api.wooVariantViewSet)
# router.register(r'wpmedia', api.wpMediaViewSet)
# router.register(r'wpmediasize', api.wpMediaSizeViewSet)
# router.register(r'pfcountry', api.pfCountryViewSet)
# router.register(r'pfstate', api.pfStateViewSet)
# router.register(r'pfsyncproduct', api.pfSyncProductViewSet)
# router.register(r'pfsyncvariant', api.pfSyncVariantViewSet)
# router.register(r'pfsyncitemoption', api.pfSyncItemOptionViewSet)
# router.register(r'pfcatalogcolor', api.pfCatalogColorViewSet)
# router.register(r'pfcatalogsize', api.pfCatalogSizeViewSet)
# router.register(r'pfcatalogfilespec', api.pfCatalogFileSpecViewSet)
# router.register(r'pfcatalogfiletype', api.pfCatalogFileTypeViewSet)
# router.register(r'pfcatalogoptiontype', api.pfCatalogOptionTypeViewSet)
# router.register(r'pfcatalogproduct', api.pfCatalogProductViewSet)
# router.register(r'pfcatalogvariant', api.pfCatalogVariantViewSet)
# router.register(r'pfstore', api.pfStoreViewSet)
# router.register(r'pfprintfile', api.pfPrintFileViewSet)
#
#
urlpatterns = (
    #     # urls for Django Rest Framework API
    #     url(r'^api/v1/', include(router.urls)),
)
#

# urls for Home Page et al.
urlpatterns += (
    url(r'^$', bzHomeView.as_view(), name='business_home_view'),
)

# URLs for Dashboard App
urlpatterns += (
    url(r'^dashboard/$', appDashboardHome.as_view(), name='app_dashboard_home'),
    # url(r'^/$', appHome.as_view(), name='app__home'),
    # url(r'^/$', appHome.as_view(), name='app__home'),
)

# URLs for Creative App
urlpatterns += (
    url(r'^creative/$',
        appCreativeHome.as_view(), name='app_creative_home'),
    url(r'^creative/collection-(?P<collection>\S+)/$',
        appCreativeHome.as_view(), name='app_creative_home'),

    url(r'^creative/collection/update/(?P<pk>\S+)/$',
        appCreativeCollectionUpdate.as_view(), name='app_creative_collection_update'),
    url(r'^creative/design/update/(?P<pk>\S+)/$',
        appCreativeDesignUpdate.as_view(), name='app_creative_design_update'),
    url(r'^creative/layout/update/(?P<pk>\S+)/$',
        appCreativeLayoutUpdate.as_view(), name='app_creative_layout_update'),

    url(r'^creative/collection/create/$',
        appCreativeCollectionCreate.as_view(), name='app_creative_collection_create'),
    url(r'^creative/design/create/$',
        appCreativeDesignCreate.as_view(), name='app_creative_design_create'),
    url(r'^creative/layout/create/$',
        appCreativeLayoutCreate.as_view(), name='app_creative_layout_create'),
)

# URLs for Product
urlpatterns += (
    url(r'^product/$', appProductHome.as_view(), name='app_product_home'),
    url(r'^product/create/$',
        bzProductFormWizard.as_view(), name="app_product_create"),
    url(r'^product/view/(?P<product>\S+)/$',
        appProductHome.as_view(), name="app_product_home"),
    url(r'^product/update/(?P<pk>\S+)/$',
        appProductUpdate.as_view(), name="app_product_update"),
)

# URLs for Store App
urlpatterns += (
    url(r'^store/$', appStoreHome.as_view(), name='app_store_home'),

    url(r'^store/brand/$', appStoreBrandList.as_view(),
        name='app_store_brand_list'),
    url(r'^store/brand/create/$', appStoreBrandCreate.as_view(),
        name='app_store_brand_create'),
    url(r'^store/brand/update/(?P<pk>\S+)/$',
        appStoreBrandUpdate.as_view(), name='app_store_brand_update'),

    url(r'^store/printful/$', appStorePFList.as_view(), name='app_store_pf_list'),
    url(r'^store/printful/create/$',
        appStorePFCreate.as_view(), name='app_store_pf_create'),
    url(r'^store/printful/update/(?P<pk>\S+)/$',
        appStorePFUpdate.as_view(), name='app_store_pf_update'),

    url(r'^store/wordpress/$', appStoreWPList.as_view(), name='app_store_wp_list'),
    url(r'^store/wordpress/create/$',
        appStoreWPCreate.as_view(), name='app_store_wp_create'),
    url(r'^store/wordpress/update/(?P<pk>\S+)/$',
        appStoreWPUpdate.as_view(), name='app_store_wp_update'),
)

# URLs for DAMS App
urlpatterns += (
    url(r'^dams/$', appDAMSHome.as_view(), name='app_dams_home'),
    url(r'^dams/printful/$', appDAMSPFList.as_view(), name='app_dams_pf_list'),
    url(r'^dams/printful/pull/$', appDAMSPFApiPull.as_view(),
        name='app_dams_pf_apipull'),
    url(r'^dams/printful/view(?P<pk>\S+)/$',
        appDAMSPFDetail.as_view(), name='app_dams_pf_detail'),
    # TODO Implement appDAMSPFCreate View
)

# URLs for Content App
urlpatterns += (
    url(r'^content/$', appContentHome.as_view(), name='app_content_home'),
)

# URLs for List App
urlpatterns += (
    url(r'^lists/$', appListsHome.as_view(), name='app_lists_home'),

    url(r'^lists/geo/$', appListGeoList.as_view(), name='app_list_geo_list'),
    url(r'^lists/geo/pull/$', appListGeoPull.as_view(),
        name='app_list_geo_apipull'),
    url(r'^lists/geo/view/(?P<pk>\S+)/$',
        appListGeoDetail.as_view(), name='app_list_geo_detail'),

    url(r'^lists/color/$', appListColorList.as_view(), name='app_list_color_list'),
    url(r'^lists/color/(?P<pk>\S+)/$',
        appListColorUpdate.as_view(), name='app_list_color_update'),

    url(r'^lists/size/$', appListSizeList.as_view(), name='app_list_size_list'),
    url(r'^lists/size/(?P<pk>\S+)/$',
        appListSizeUpdate.as_view(), name='app_list_size_update'),

    url(r'^lists/filespec/$', appListFileSpecList.as_view(),
        name='app_list_filespec_list'),
    url(r'^lists/filespec/create/$',
        appListFileSpecCreate.as_view(), name='app_list_filespec_create'),
    url(r'^lists/filespec/(?P<pk>\S+)/$',
        appListFileSpecUpdate.as_view(), name='app_list_filespec_update'),

    url(r'^lists/shipping/$', appListShippingList.as_view(),
        name='app_list_shipping_list'),
    url(r'^lists/shipping/create/$', appListShippingCreate.as_view(),
        name='app_list_shipping_create'),
    url(r'^lists/shipping/(?P<pk>\S+)/$',
        appListShippingUpdate.as_view(), name='app_list_shipping_update'),
    url(r'^lists/shipping/push/$', appListShippingPush.as_view(),
        name='app_list_shipping_push'),
    url(r'^lists/shipping/pull/$', appListShippingPull.as_view(),
        name='app_list_shipping_pull'),

    url(r'^lists/category/$', appListCategoryList.as_view(),
        name='app_list_category_list'),
    url(r'^lists/category/create/$', appListCategoryCreate.as_view(),
        name='app_list_category_create'),
    url(r'^lists/category/(?P<pk>\S+)/$',
        appListCategoryUpdate.as_view(), name='app_list_category_update'),
    url(r'^lists/category/$', appListCategoryPush.as_view(),
        name='app_list_category_push'),
    url(r'^lists/category/$', appListCategoryPull.as_view(),
        name='app_list_category_pull'),

    url(r'^lists/tag/$', appListTagList.as_view(), name='app_list_tag_list'),
    url(r'^lists/tag/create/$', appListTagCreate.as_view(),
        name='app_list_tag_create'),
    url(r'^lists/tag/(?P<pk>\S+)/$',
        appListTagUpdate.as_view(), name='app_list_tag_update'),
    url(r'^lists/tag/$', appListTagPush.as_view(), name='app_list_tag_push'),
    url(r'^lists/tag/$', appListTagPull.as_view(), name='app_list_tag_pull'),

    url(r'^lists/cprod/$', appListCatProductList.as_view(),
        name='app_list_cprod_list'),
    url(r'^lists/cprod/pull/$', appListCatProductPull.as_view(),
        name="app_list_cprod_apipull"),
    url(r'^lists/cprod/(?P<pk>\S+)/$',
        appListCatProductUpdate.as_view(), name='app_list_cprod_update'),

    url(r'^lists/attribute/$', appListAttributeList.as_view(),
        name='app_list_attribute_list'),
    url(r'^lists/attribute/(?P<pk>\S+)/$',
        appListAttributeUpdate.as_view(), name='app_list_attribute_update'),
)


# Old data patterns

urlpatterns += (
    # urls for bzBrand
    url(r'^bzbrand/$', bzBrandListView.as_view(), name='business_bzbrand_list'),
    url(r'^bzbrand/create/$', bzBrandCreateView.as_view(),
        name='business_bzbrand_create'),
    url(r'^bzbrand/detail/(?P<pk>\S+)/$',
        bzBrandDetailView.as_view(), name='business_bzbrand_detail'),
    url(r'^bzbrand/update/(?P<pk>\S+)/$',
        bzBrandUpdateView.as_view(), name='business_bzbrand_update'),
)

urlpatterns += (
    # urls for bzCreativeCollection
    url(r'^bzcreativecollection/$', bzCreativeCollectionListView.as_view(),
        name='business_bzcreativecollection_list'),
    url(r'^bzcreativecollection/create/$',
        bzCreativeCollectionCreateView.as_view(), name='business_bzcreativecollection_create'),
    url(r'^bzcreativecollection/detail/(?P<pk>\S+)/$',
        bzCreativeCollectionDetailView.as_view(), name='business_bzcreativecollection_detail'),
    url(r'^bzcreativecollection/update/(?P<pk>\S+)/$',
        bzCreativeCollectionUpdateView.as_view(), name='business_bzcreativecollection_update'),
)

urlpatterns += (
    # urls for bzCreativeDesign

src/storemanager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import business.urls
# from . import views

urlpatterns = [
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(business.urls, namespace='business')),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/business/views/app_content.py
from django.core.urlresolvers import reverse

from django.http import HttpResponse

from django.shortcuts import render

from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic import DetailView, ListView, UpdateView, CreateView

from django_tables2 import *

from business.models import *
from business.forms import *
from business.tables import *
from business.helper_backend import commonListView


class appContentHome(TemplateView):
    template_name = "content/page.html"

    def get_context_data(self, **kwargs):
        context = super(appContentHome, self).get_context_data(**kwargs)
        context['active_app'] = "content"
        context['active_apptitle'] = "Content Editor"
        return context

src/business/views/app_dams.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse

from django.shortcuts import render, redirect

from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.base import RedirectView

from django_tables2 import *

from business.models import *
from business.forms import *
from business.tables import *
from business.filters import *

from business.helper_backend import commonListView, commonUpdateView, commonCreateView
from django.contrib import messages


class appDAMSCommonListView(commonListView):
    active_app = 'dams'
    active_apptitle = 'Digital Asset Management'
    object_icon = 'picture'


class appDAMSCommonUpdateView(commonUpdateView):
    active_app = 'dams'
    active_apptitle = 'Digital Asset Management'
    object_icon = 'picture'


class appDAMSCommonCreateView(commonCreateView):
    active_app = 'dams'
    active_apptitle = 'Digital Asset Management'
    object_icon = 'picture'

# ======


class appDAMSHome(View):
    def get(self, request):
        return redirect(reverse('business:app_dams_pf_list'))


class appDAMSPFList(appDAMSCommonListView):
    model = pfPrintFile
    table_class = pfPrintFileTable
    object_name = "Printful File"
    action_list = [
        {
            'btn_class': 'default',
            'view': 'business:app_dams_pf_apipull',
            'text': 'Sync'
        },
    ]


class appDAMSPFDetail(appDAMSCommonUpdateView):
    model = pfPrintFile
    form_class = pfPrintFileForm
    object_name = "Print File"
    success_url = reverse_lazy("business:app_dams_pf_list")
    action_list = reverse_lazy("business:app_dams_pf_list")


class appDAMSPFCreate(appDAMSCommonCreateView):
    # TODO Implement appDAMSPFCreate View
    pass


class appDAMSPFApiPull(View):
    def get(self, request):
        try:
            sCounter = 0
            # TODO Add ability to sync only one Printful store's PrintFilesq
            # (currently syncs all stores).
            for s in pfStore.objects.all():
                pfPrintFile.api_pull(s)
                sCounter += 1
            messages.add_message(request, messages.SUCCESS,
                                 "Success! Updated print files for {} stores.".format(sCounter))
        except Exception as e:
            messages.add_message(request, messages.ERROR,
                                 'API call failed. {}'.format(e))
        return redirect('business:app_dams_pf_list')

src/business/views/app_dashboard.py
from django.core.urlresolvers import reverse

from django.http import HttpResponse

from django.shortcuts import render

from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic import DetailView, ListView, UpdateView, CreateView

from django_tables2 import *

from business.models import *
from business.forms import *
from business.tables import *
from business.helper_backend import commonListView


class appDashboardHome(TemplateView):
    # template_name = "business/object_list.html"
    template_name = "content/page.html"

    def get_context_data(self, **kwargs):
        context = super(appDashboardHome, self).get_context_data(**kwargs)
        context['active_app'] = "dashboard"
        context['active_apptitle'] = "Dashboard"
        return context

src/business/templates/app_creative/home.html
{% extends "base.html" %}
{% load staticfiles crispy_forms_tags humanize %}
{% load render_table from django_tables2 %}
{% block title %}{{ block.super }}{{ active_apptitle }}{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" %}
{% endblock %}

{% block navbar-secondary %}{% endblock %}

{% block container %}
<form method="post">
  <div class="container business-head">
    <div class="row">
      <div class="col-md-12">
        <h3><small><span class="glyphicon glyphicon-picture"></span></small>
          Creative Management {% if active_collection %}<small>/ {{ active_collection }}</small>{% endif %}
          <span class="pull-right">
            <div class="btn-group" role="group">
              <a href="{% url 'business:app_creative_collection_create' %}" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus"></span> New</a>
              {% if active_collection %}
              <a href="{% url 'business:app_creative_collection_update' active_collection.pk %}" role="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit</a>
              {% endif %}
            </div>
            {% if active_collection %}
            <div class="btn-group" role="group">
              <a href="{% url 'business:app_creative_design_create' %}?collection={{ active_collection.pk }}" role="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Design</a>
            </div>
            <div class="btn-group" role="group">
              <a href="{% url 'business:app_creative_layout_create' %}?collection={{ active_collection.pk }}" role="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Layout</a>
            </div>
            {% endif %}
          </span>
        </h3>
      </div>
    </div>
  </div>
  <div class="container business-body">
    {% if active_collection %}
    <div class="row">
      <div class="col-md-3" id="navSidebar">
        <div class="list-group">
          {% for cc in creativecollections %}
          <a href="{% url 'business:app_creative_home' collection=cc.pk %}" class="list-group-item {% if active_collection == cc %} active{% endif %}">
            <span class="badge" data-toggle="tooltip" data-placement="bottom" title="{{ cc.num_designs }} Designs / {{ cc.num_layouts }} Layouts">
              {{ cc.num_designs }} / {{ cc.num_layouts }}</span>
            {{ cc }}
          </a>
          {% endfor %}
        </div>
      </div>
      <div class="col-md-9" id="pageContent">

        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active"><a href="#detail" aria-controls="detail" role="tab" data-toggle="tab">About</a></li>
          <li role="presentation"><a href="#designs" aria-controls="designs" role="tab" data-toggle="tab">Designs ({{ active_collection.num_designs }})</a></li>
          <li role="presentation"><a href="#layouts" aria-controls="layouts" role="tab" data-toggle="tab">Layouts ({{ active_collection.num_layouts }})</a></li>
        </ul>

        <div class="tab-content">

          <div role="tabpanel" class="tab-pane active" id="detail">
            <table class="table table-striped">
              <tr>
                <th>Name</th>
                <td>{{ active_collection.name }}</td>
              </tr>
              <tr>
                <th>SKU Code Base</th>
                <td>{{active_collection.code}}</td>
              </tr>
              <tr>
                <th>Brand</th>
                <td><a href="{% url 'business:app_store_brand_update' pk=active_collection.bzbrand.pk %}">{{active_collection.bzbrand}}</a></td>
              </tr>
              <tr>
                <th>Designs</th>
                <td>{{active_collection.num_designs|apnumber|title}}</td>
              </tr>
              <tr>
                <th>Layouts</th>
                <td>{{active_collection.num_layouts|apnumber|title}}</td>
              </tr>
              <tr>
                <th>Created</th>
                <td>{{ active_collection.date_added|naturaltime|title }}</td>
              </tr>
              <tr>
                <th>Updated</th>
                <td>{{ active_collection.date_updated|naturaltime|title }}</td>
              </tr>
            </table>
          </div>

          <div role="tabpanel" class="tab-pane" id="designs">
            {% render_table table_designs %}
          </div>

          <div role="tabpanel" class="tab-pane" id="layouts">
            {% render_table table_layouts %}
          </div>

        </div>
      </div>
    </div>
    {% else %}
    <h4>No Collections Found</h4>
    <p>Get started by clicking that little "+New" button above.</p>
    {% endif %}

  </div>
</form>
{% endblock %}

{% block scripts %}
<script>$(function () { $('[data-toggle="tooltip"]').tooltip() })</script>
{% endblock %}